### ISSUE TITLE
Decide project layout

### ISSUE THREAD

**Issue by StevenMDixon** [catnap89/Snippit-Project#6]
Do we want multiple html pages? 

Or 

Do we want to use Jquery to show and hide sections?

**Comment by ghost** [comment]
I want the single page as that would make it easier for me to get lol
But it's up to you guys really!

**Comment by StevenMDixon** [comment]
I agree on single page, we can close this issue if we all agree.

**Comment by catnap89** [comment]
Okay, let's start with single page and we can expand later if we need to.
