### ISSUE TITLE
Add Code mirror CDN

### ISSUE THREAD

**Issue by StevenMDixon** [catnap89/Snippit-Project#9]
Need to add Code Mirror CDN to Index.html

https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.48.2/codemirror.min.js

https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.48.2/codemirror.min.css

User Documentation: https://codemirror.net/doc/manual.html

This will let us add code mirror into our app, the highlighting for the code is done by the css above.

**Comment by catnap89** [comment]
Wait, I just added like 500 files for Codemirror by downloading them.
Is this CDN same as linking downloaded files?

**Comment by StevenMDixon** [comment]
Nope

We would need to add something like: 

```
<script src="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.48.2/codemirror.js"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.48.2/codemirror.css">
<script src="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.48.2/mode/javascript/javascript.js"></script>
```

from here https://cdnjs.com/libraries/codemirror
